name: MuezliAnnouncer
main: me.ScottSpittle.MuezliAnnouncer.MuezliAnnouncer
authors: [ScottSpittle]
version: 1.1
description: Muezli's Auto Announcer
commands:
  announce:
    description: Reload plugin Config
    usage: |
        /<command> reload - reloads config.
        /<command> add [announcement message]- Adds an announcement to the config.
        /<command> set <prefix/delay> [prefix/delay]- Change the prefix or delay of the announcements.