name: MuezliAnnouncer
main: me.ScottSpittle.MuezliAnnouncer.MuezliAnnouncer
authors: [ScottSpittle]
version: 1.1
description: Muezli's Auto Announcer
commands:
  announce:
    description: Reload plugin Config
    usage: |
        /<command> reload - reloads config.